config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :name, presence: true
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true,
                    length: {minimum: 15, maximum: 75},
                    uniqueness: {case_sensitive: false}
  validates :blog_author, presence: true,
                          length: {minimum: 5},
                          format: {without: /\d/, message: "No numbers bro."},
                          uniqueness: {case_sensitive: false}
  validates :content, presence: true,
                      length: {minimum: 250, maximum: 2000},
                      uniqueness: {case_sensitive: false}

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @post = Post.find(params[:post_id])
  end

  # GET /comments/new
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build
  end

  # GET /posts/1/comments/21/edit
  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.save
    redirect_to post_path(@post)
  end
  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to posts_path(@post)
    else
      render 'new'
    end

  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    post = Post.find(params[:post_id])
    @comment = post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(post)
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name,:email, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.page(params[:page]).per(2).order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
      flash[:notice] = "You've published your post successfully."
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
    flash[:notice] = "You've deleted your post successfully."
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
      flash[:notice] = "You've updated your post successfully."
    else
      render 'new'
    end
  end
private
    def post_params
      params.require(:post).permit(:title, :blog_author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<% if flash[:notice] %>
       <div class="alert alert-success alert-dismissable">
         <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
         <strong><%= flash[:notice] %></strong>
       </div>
     <% end %>
<section class="container-fluid ">
<%= form_for ([@post,@post.comments.build]),:validate => true, :html=>{:class =>"form"} do |f| %>
<section class="content-box">
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
</section>
<section class="content-box">
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
</section>
<section class="content-box">
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content, :class =>"content-area" %>
  </p>
</section>
<footer class="form-bottom">

    <%= f.submit 'Submit', :class =>"btn btn-default"%>
    <%= link_to 'Go Back', post_path(@post), class: "btn btn-default" %>
<% end %>
</footer>

</section>

app/views/comments/edit.html.erb
<header class="row clear">
<h1>Editing Comment</h1>
</header>

<section class="container-fluid ">
<%= form_for ([@post,@comment]),:validate => true, :html=>{:class =>"form"} do |f| %>
<section class="content-box">
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
</section>
<section class="content-box">
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
</section>
<section class="content-box">
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content, :class =>"content-area" %>
  </p>
</section>
<footer class="form-bottom">

    <%= f.submit 'Submit', :class =>"btn btn-default"%>
    <%= link_to 'Go Back', post_path(@post), class: "btn btn-default" %>
<% end %>
</footer>

</section>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<header class="row clear">
  <h1>What would you like to comment?</h1>
</header>

<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "index" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag :defaults, "rails.validations" %>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body class="container-fluid">
    <header class="row banner">

      <section class="col-xs-4 left-top">
        <p>Hey welcome to my<br /> humble blog!</p>
      </section>
      <section class="col-xs-4 middle-top">
          <%= link_to image_tag("http://i.imgur.com/Ghn3XpP.png", :alt => "Ash Profile Photo",
          :class => "img-circle img-responsive profile-image"), posts_path %>
      </section>
      <section class="col-xs-4 right-top">
        <%= link_to 'Create a blog post here', new_post_path, class:"btn btn-default btn-create" %>
      </section>
    </header>

    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.erb
  <section class="container-fluid ">
  <%= form_for @post, :html => {:class =>"form"}, :validate => true do |f| %>
  <section class="content-box">
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
  </section>
  <section class="author_name">
    <p>
      <%= f.label :blog_author %><br>
      <%= f.text_field :blog_author %>
    </p>
  </section>
  <section class="content-box">
    <p>
      <%= f.label :content %><br>
      <%= f.text_area :content, :class =>"content-area" %>
    </p>
  </section>
  <footer class="form-bottom">

      <%= f.submit 'Submit', :class =>"btn btn-default"%>
      <%= link_to 'Go Back', posts_path, class: "btn btn-default" %>
  <% end %>
</footer>

</section>

app/views/posts/edit.html.erb
<section class="clear">
  <h1>Edit your blog post</h1>
</section>

<%= render 'form' %>

app/views/posts/index.html.erb
<section class="container-fluid main-container">
  <section class="container content-body">
    <section class="container content-post">
      <% if flash[:notice] %>
             <div class="alert alert-success alert-dismissable">
               <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
               <strong><%= flash[:notice] %></strong>
             </div>
           <% end %>
      <article class="blog-post">
         <% @posts.each do |post| %>
         <header class="blog-header"><%= post.title %></header>
          <section class="blog-author">Posted by: <%= post.blog_author %></section>
          <section class="blog-content"><%= post.content %></section>
           <footer class="icons">
             <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
             <%= link_to 'Comments', post_path(post) %>
             <span>&nbsp&nbsp&nbsp</span>
             <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
             <%= link_to 'Edit', edit_post_path(post) %>
             <span>&nbsp&nbsp&nbsp</span>
             <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    <%= link_to 'Delete', post_path(post),
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %>
           </footer>
           <hr />
         <% end %>
      </article>
      <footer class="page-footer">
        <a href="https://www.linkedin.com/in/ash-rhazaly-9445987b/" class="btn btn-social-icon-btn-lg btn-linkedin">
            <span class="fa fa-linkedin"></span>
        </a>
        <a href="https://github.com/AshRhazaly" class="btn btn-social-icon-btn-lg btn-github">
            <span class="fa fa-github"></span>
        </a>

      </footer>
    </section>
  </section>
</section>
    <%= paginate @posts %>

app/views/posts/new.html.erb
<header class="row clear">
  <h1>What would you like to post?</h1>
</header>
<%= render 'form' %>

app/views/posts/show.html.erb
<section class="container-fluid main-container">
<section class="container content-body">
<section class="container content-post">
<header class="blog-header">
  <strong>Title:</strong>
  <%= @post.title %>
</header>

<section class="blog-author">
  <strong>Author:</strong>
  <%= @post.blog_author %>
</section>

<section class="blog-content">
  <%= @post.content %>
</section>
<hr />
<section class="blog-content">
<h4>Comments</h4>
<% @post.comments.each do |comment| %>
  <p>
    <strong>Name:</strong>
    <%= comment.name %>
  </p>
  <p>
    <strong>Email:</strong>
    <%= comment.email %>
  </p>
  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>
  <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
  <%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
  <%= link_to 'Delete', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

</section>
<hr />
<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
<%= link_to 'Add a new comment', new_post_comment_path(@post) %>
<span>&nbsp;</span>
<span class="glyphicon glyphicon-step-backward" aria-hidden="true"></span>
<%= link_to 'Back', posts_path %>
</section>
</section>


</section>